spring.application.name=crm
# ===============================
# JWT CONFIG
# ===============================
jwt.secret=Y2xhdmVfcG9jaGlfbW92aWxfc2VjcmV0XzI1Nl9iaXRzX3NlZ3VyYQ==
jwt.expiration=86400000

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/meyi_pos
spring.datasource.username=postgres
spring.datasource.password=Cotemar19$

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8084

# Configuración de Firebase
firebase.config.path=classpath:firebase-config.json

# Tokens de WhatsApp - Usando tus valores reales
